# Generated by Django 5.1.2 on 2025-11-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome amigável da conta (ex.: Outlook Pessoal, Conta LBC, etc.)', max_length=100)),
                ('host', models.CharField(default='outlook.office365.com', help_text='Servidor IMAP (ex.: outlook.office365.com)', max_length=255)),
                ('port', models.IntegerField(default=993, help_text='Porta IMAP (normalmente 993 para IMAPS)')),
                ('username', models.CharField(help_text='Nome de utilizador / endereço de email', max_length=255)),
                ('password', models.CharField(help_text="Password ou token de aplicação (não usar password 'crua' em produção)", max_length=255)),
                ('folder', models.CharField(default='INBOX', help_text='Pasta IMAP a monitorizar (ex.: INBOX, Faturas, etc.)', max_length=100)),
                ('use_ssl', models.BooleanField(default=True, help_text='Usar ligação segura (SSL/TLS) para IMAP')),
                ('active', models.BooleanField(default=True, help_text='Se desactivar, a conta deixa de ser processada pelo AttachFlow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta de Email',
                'verbose_name_plural': 'Contas de Email',
            },
        ),
    ]
