# Generated by Django 5.1.2 on 2025-11-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='cached_folders',
            field=models.JSONField(blank=True, default=list, help_text='Lista de pastas IMAP descobertas no último teste de ligação.'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_connection_message',
            field=models.TextField(blank=True, help_text='Mensagem do último teste (sucesso/erro).'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_connection_ok',
            field=models.BooleanField(default=False, help_text='Resultado do último teste de ligação.'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='name',
            field=models.CharField(help_text='Nome amigável da conta (ex.: Outlook Pessoal, Conta LBC, etc.)', max_length=150),
        ),
    ]
