# Generated by Django 5.1.2 on 2025-11-24 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome amigável da regra (ex.: Faturas Continente, Relatórios Mensais, etc.)', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Se desactivada, a regra não será executada.')),
                ('imap_folder', models.CharField(default='INBOX', help_text='Pasta IMAP onde esta regra será aplicada (ex.: INBOX, INBOX/Faturas, Faturas).', max_length=150)),
                ('from_contains', models.CharField(blank=True, help_text='Filtro por remetente (contém). Ex.: faturas@supermercado.pt', max_length=255)),
                ('subject_contains', models.CharField(blank=True, help_text="Filtro por assunto (contém). Ex.: 'Fatura' ou 'Factura'", max_length=255)),
                ('filename_regex', models.CharField(blank=True, help_text='Expressão regular para o nome de ficheiro do anexo. Ex.: ^Fatura_.*\\.pdf$', max_length=255)),
                ('dest_folder', models.CharField(help_text='Pasta local para onde os anexos serão descarregados.', max_length=500)),
                ('mark_as_read', models.BooleanField(default=True, help_text='Marcar email como lido após processamento.')),
                ('move_to_folder', models.CharField(blank=True, help_text='Se preenchido, mover o email para esta pasta IMAP após processamento.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Conta de email à qual esta regra pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.emailaccount')),
            ],
            options={
                'verbose_name': 'Regra de Captura',
                'verbose_name_plural': 'Regras de Captura',
            },
        ),
    ]
