# Generated by Django 5.1.2 on 2025-11-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailaccount_cached_folders_and_more'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='filename_template',
            field=models.CharField(default='{date:%Y.%m.%d %H.%M} - {rule_name}{index}{ext}', help_text='Template para o nome do ficheiro. Placeholders suportados: {date:FORMATO}, {rule_name}, {account_name}, {original_name}, {index}, {ext}.', max_length=255),
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Em execução'), ('SUCCESS', 'Sucesso'), ('ERROR', 'Erro')], default='RUNNING', max_length=20)),
                ('emails_processed', models.IntegerField(default=0)),
                ('attachments_downloaded', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro, se a execução terminar em erro.')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='rules.rule')),
            ],
            options={
                'verbose_name': 'Execução de Regra',
                'verbose_name_plural': 'Execuções de Regras',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Caminho final do ficheiro no sistema de ficheiros.', max_length=500)),
                ('file_name', models.CharField(help_text='Nome final do ficheiro (sem caminho).', max_length=255)),
                ('original_filename', models.CharField(help_text='Nome original do anexo no email.', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sender', models.CharField(blank=True, help_text='Remetente (From) do email.', max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Assunto do email.', max_length=500)),
                ('folder', models.CharField(help_text='Pasta IMAP em que o email foi encontrado.', max_length=150)),
                ('uid', models.CharField(help_text='UID IMAP da mensagem.', max_length=100)),
                ('message_id', models.CharField(blank=True, help_text='Cabeçalho Message-ID da mensagem.', max_length=255)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_logs', to='accounts.emailaccount')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_logs', to='rules.rule')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rules.jobexecution')),
            ],
            options={
                'verbose_name': 'Anexo Descarregado',
                'verbose_name_plural': 'Anexos Descarregados',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(help_text='Pasta IMAP em que o email foi encontrado.', max_length=150)),
                ('uid', models.CharField(help_text='UID IMAP da mensagem.', max_length=100)),
                ('message_id_header', models.CharField(blank=True, help_text='Valor do cabeçalho Message-ID (se disponível).', max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='accounts.emailaccount')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to='rules.rule')),
            ],
            options={
                'verbose_name': 'Email Processado',
                'verbose_name_plural': 'Emails Processados',
                'unique_together': {('account', 'folder', 'uid', 'rule')},
            },
        ),
    ]
